Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: 2010-09-09

Resources:
  SimpleVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16

  SimpleSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref SimpleVpc
      AvailabilityZone: 'usw2-az1'
