AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
Resources:
  LambdaTrustRole:
    Type: AWS::IAM::Role
    Description: Need a role for lambda, here is a role for lambda.
    Properties:
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: LambdaPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
            Effect: Allow
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
  ReadLayerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: golayerdelete
      CodeUri: s3://sean-myers-pdx/11952972872fdece2da69b4d31dc2659
      Handler: app
      Runtime: go1.x
      Layers:
      - Ref: ExampleLayer
      Role:
        Fn::GetAtt:
        - LambdaTrustRole
        - Arn
  ExampleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
      - go1.x
      ContentUri: s3://sean-myers-pdx/b10a6e433cc92714082239b445ea57c6
      LicenseInfo: Apache 2.0, the super open one
      LayerName: example
